# Generated by Django 5.1 on 2024-09-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulink',
            options={'verbose_name': 'Menu Links', 'verbose_name_plural': 'Menu Links'},
        ),
    ]
