# Generated by Django 5.1 on 2024-09-08 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_menulink_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulink',
            options={'verbose_name': 'Menu Link', 'verbose_name_plural': 'Menu Links'},
        ),
    ]
