# Generated by Django 5.1 on 2024-09-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True)),
                ('is_published', models.BooleanField(default=False, help_text='This field must be checked for the page to be displayed publicly. Glu Glu, Yeh Yeh.')),
                ('content', models.TextField()),
            ],
        ),
    ]
